version: '3'

services:

  bifrost:
    image: bifrost
    container_name: bifrost
    build:
      context: './docker'
      dockerfile: Dockerfile
    depends_on:
      - bifrost-mysql
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:80

  bifrost-mysql:
    image: mysql:5.7
    container_name: bifrost-mysql
    ports:
      - 8080:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret

  bifrost-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'bifrost-phpmyadmin'
    depends_on:
      - bifrost-mysql
    ports:
      - 8081:80
    environment:
      PMA_HOST: bifrost-mysql
      PMA_PORT: 3306
