#!/bin/bash
cd /var/www/html
## Copy config files
cp /var/www/html/.env.example /var/www/html/.env
cp /var/www/html/config/gateways.sample.php /var/www/html/config/gateways.php
## Dependencies
composer install
## Generate artisan key
php artisan key:generate
## Database
php artisan migrate
## Run seeder
php artisan db:seed
## Run queue
php artisan optimize:clear
php artisan config:cache
php artisan queue:work bifrost-redis --tries=3 --timeout=90
